spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  jpa:
    show-sql: false

  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 900000
      refresh-expiration: 604800000

logging:
  level:
    com.novapass: INFO
    org.springframework: WARN
    org.hibernate: WARN

server:
  error:
    include-message: never
    include-binding-errors: never
